### ISSUE TITLE
Problem with Hogfather 5.1

### ISSUE THREAD

**Issue by Capbat99** [GJRobert/dokuwiki-plugin-formatplus2#2]
I am receiving following errors when activating Plugin.

[20-Jun-2020 11:37:22 America/Toronto] PHP Fatal error:  Class FormattingPlus_Syntax_Plugin contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (dokuwiki\Parsing\ParserMode\AbstractMode::getSort) in /home3/capbat/public_html/DOK2/dokuwiki/lib/plugins/formatplus2/formatting.php on line 0

[20-Jun-2020 12:00:14 America/Toronto] PHP Fatal error:  Declaration of action_plugin_formatplus::register() must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in /home3/capbat/public_html/DOK2/dokuwiki/lib/plugins/formatplus/action.php on line 0

FYI

Bat

**Comment by GJRobert** [comment]
Hi there,
Thanks a lot for posting here.

Confirming this issue on my machine (I have installed a new Hogfather RC instance on my machine, and installed formatplus2 in it). My log messages:

> [23-Jun-2020 10:50:24 Asia/Taipei] PHP Fatal error:  Class FormattingPlus_Syntax_Plugin contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (dokuwiki\Parsing\ParserMode\AbstractMode::getSort) in /Users/gjrobert/web/dw-hogfather/lib/plugins/formatplus2/formatting.php on line 137

I will have to seek help to tackle down this issue, because I know very little in PHP programming. I cannot assure how long this may take.

Actually I dare not to upgrade to Hogfather and is still using Greebo for my production DW, because I cannot hold to see so many plugins having trouble at the same time.

By the way, you seem to be using formatplus2 with formatplus side-by-side. Perhaps you can uninstall formatplus(1) because the two plugins overlap.

**Comment by Capbat99** [comment]
Hi.

I have removed both of them now. I now I have tried them both, but I am Not sure if at any time they where both active at the same time, sorry. 

schplurtz is also working on this.

 

Thanks for your help.

 

Bat

 

 

 

De : GHSRobert Ciang [mailto:notifications@github.com] 
Envoyé : June 22, 2020 22:14
À : GJRobert/dokuwiki-plugin-formatplus2
Cc : Capbat99; Author
Objet : Re: [GJRobert/dokuwiki-plugin-formatplus2] Problem with Hogfather 5.1 (#2)

 

Hi there,
Thanks a lot for posting here.

Just to exclude other possibilities:
Are you using formatplus2 with formatplus side-by-side? Can you check out if your formatplus is disabled or not? If it is enabled, can you try disabling formatplus, leaving just formatplus2 enabled, and see if you still get the same errorlog messages?

Tks

**Comment by GJRobert** [comment]
Hi @Capbat99 it's now fixed. (PR #3) The information on DokuWiki official wiki is updated, and people can now update with Extension Manager. I have incorporated schplurtz's fix into my fork (he has worked directly on Formatplus(1) but we have a newer fork with some small works here). Thanks a lot for pointing me to the direction.

I'm glad that it's so simple to just add a `abstract` keyword in front of one line and the plugin is back to life again.
